api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls')),
]

cloudinary_app/urls.py
from django.urls import path
from .views import home,ai_task,ai_upscale,enhance,bgremove,genfill,genreplace




urlpatterns = [


    path('',home,name="home"),
    path('process/<str:img_id>/',ai_task,name="process"),
    path('upscale/<str:pID>/',ai_upscale,name="ups"),
    path('enhance/<str:pID>/',enhance,name="enhance"),
    path('fill/<str:pID>/',genfill,name="fill"),
    path('replace/<str:pID>/',genreplace,name="replace"),
    path('bggrmv/<str:pID>/',bgremove,name="bgrmv"),
]


app_name="cloudinary"

sceloimg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cloudinary_app.urls',namespace="cloud"))
]



if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cloudinary_app/models.py
from django.db import models

# Create your models here.

cloudinary_app/forms.py
from django import forms

class ImageForm(forms.Form):
    image = forms.ImageField()

cloudinary_app/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.core.cache import cache
from django.http import HttpResponseForbidden
from django.urls import reverse
import cloudinary.uploader
import cloudinary.api
from .forms import ImageForm
import cloudinary
import uuid
from cloudinary import CloudinaryImage
from django.contrib import messages
import datetime
from ipware import get_client_ip

# Configuration       
cloudinary.config( 
    cloud_name = "dgpcfijvz", 
    api_key = "315853338388874", 
    api_secret = "llbSbjeYlCnHKyMCbYGX1qN6l7Y", # Click 'View API Keys' above to copy your API secret
    secure=True
)



def get_ip(request):
    ip, is_routable = get_client_ip(request)
    print(is_routable)
    return ip






def home(request):
    if request.method == 'POST':
        form = ImageForm(request.POST,request.FILES)
        if form.is_valid():
            image_file = request.FILES["image"]
            request.session["uploaded_image"] = image_file.read()  # Save the binary content
            request.session["image_name"] = image_file.name 
            uploaded_image = request.session.get("uploaded_image")
            image_name = request.session.get("image_name")

            if uploaded_image and image_name:
                # Upload the image to Cloudinary
                try:
                    uid = str(uuid.uuid4())
                    response = cloudinary.uploader.upload(uploaded_image, public_id=uid)
                    img_id = uid

                    # Clear the session data
                    del request.session["uploaded_image"]
                    del request.session["image_name"]
                    return redirect(reverse("cloud:process", kwargs={"img_id": img_id}))
                except Exception as e:
                    
                    messages.error(request,"There is a problem with the API. Please try again leter.")
                    return redirect("cloud:home")

    form = ImageForm()
    
    context = {
        "form":form,
    }
    return render(request,"cloud/home.html",context=context)


def ai_task(request,img_id):
    # Get the user's IP address
    ip_address = get_ip(request)
    # Generate a unique cache key using the IP and current date
    today = datetime.date.today()
    cache_key = f"view_access_{ip_address}_{today}"
    
    # Get the current access count (default is 0)
    access_count = cache.get(cache_key, 0)
    
    if access_count >= 5:
        messages.info(request,"You have reached the maximum number of allowed accesses for today.")
        return redirect("cloud:home")
    
    # Increment the count and set it in the cache with a 24-hour timeout
    cache.set(cache_key, access_count + 1, timeout=24*3600)  # Timeout is 24 hours in seconds
    try:
        img = cloudinary.api.resource(str(img_id))
        img_url = img["secure_url"]
    except Exception as e:
        messages.error(request,"There is a problem with the API. Please try again leter.")
        return redirect("cloud:home")
    if access_count == 0:
        messages.info(request,"This was your last upload of the day.")
    messages.info(request,f"Access allowed. You have {5 - access_count - 1} accesses remaining today.")
    return render(request,"cloud/ai.html",context={"img":img_url,"pID":img_id})





def ai_upscale(request,pID):
    if request.method == 'POST':
        try:
            result = CloudinaryImage(f'{pID}').image(effect="upscale")
            url = f"{result[10:-3]}"
            return redirect(url)
        except Exception as e:
            messages.error(request,"There is a problem with the API. Please try again leter.")
            return redirect("cloud:home")


def enhance(request,pID):
    if request.method == 'POST':
        try:
            result =CloudinaryImage(f"{pID}").image(effect="enhance")
            url = f"{result[10:-3]}"
            return redirect(url)
        except Exception as e:
            messages.error(request,"There is a problem with the API. Please try again leter.")
            return redirect("cloud:home")

def genfill(request,pID):
    if request.method == 'POST':
        try:
            result =CloudinaryImage(f"{pID}").image(aspect_ratio="1:1", gravity="center", background="gen_fill", crop="pad")
            url = f"{result[10:-3]}"
            return redirect(url)
        except Exception as e:
            messages.error(request,"There is a problem with the API. Please try again leter.")
            return redirect("cloud:home")

def genreplace(request,pID):
    if request.method == "POST":
        replace_from = request.POST["from"]
        replace_to = request.POST["to"]
        try:
            result =CloudinaryImage(f"{pID}").image(effect=f"gen_replace:from_{replace_from};to_{replace_to}")
            url = f"{result[10:-3]}"
            return redirect(url)
        except Exception as e:
            messages.error(request,"There is a problem with the API. Please try again leter.")
            return redirect("cloud:home")


def bgremove(request,pID):
    if request.method == 'POST':
        try:
            result =CloudinaryImage(f"{pID}").image(effect="background_removal")
            url = f"{result[10:-3]}"
            return redirect(url)
        except Exception as e:
            messages.error(request,"There is a problem with the API. Please try again leter.")
            return redirect("cloud:home")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "./css/output.css" %}">
    <link rel="shortcut icon" href="{% static "./img/favicon.ico" %}" type="image/x-icon">
  </head>
  <body>

  
<header>
  <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800 shadow-xl ">
      <div class="flex flex-wrap justify-center md:justify-between items-center mx-auto max-w-screen-xl min-h-[4rem]">
          <a href="{% url "cloud:home" %}" class="flex items-center">
              <img src="{% static "./img/logo.png" %}" class="mr-3 h-16 w-10 object-cover" alt="Flowbite Logo" />
              <div class="flex flex-col items-center justify-center gap-1">
                <span class="self-center text-3xl font-semibold whitespace-nowrap dark:text-white">SceloImage</span>
                <span class="self-center text-lg font-normal text-gray-500 whitespace-nowrap dark:text-white">Upscale Images</span>
              </div>
                      </a>
          <div class="flex items-center lg:order-2">
            <button id="theme-toggle" type="button" class="text-gray-500 mx-4 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
              <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
              <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
          </button>
          
              <a href="mailto:talhashahidkhan49@gmail.com" target="_blank" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Feedback</a>
              <button data-collapse-toggle="mobile-menu-2" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-2" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                  <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
              </button>
          </div>
          <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
              <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                  <li>
                      <a href="{% url "cloud:home" %}" class="block py-2 pr-4 pl-3 text-white rounded bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:p-0 dark:text-white" aria-current="page">Home</a>
                  </li>
                  
              </ul>
          </div>
      </div>
  </nav>
  <section class="bg-gray-50 dark:bg-gray-900">
    {% include "extra/msg.html" %}
  </section>
</header>





      {% block body %}{% endblock body %}

    
<footer class="p-4 bg-gray-50 sm:p-6 dark:bg-gray-800">
  <div class="mx-auto max-w-screen-xl">
      <div class="md:flex md:justify-between">
          <div class="mb-6 md:mb-0">
            <a href="{% url "cloud:home" %}" class="flex items-center">
              <img src="{% static "./img/logo.png" %}" class="mr-3 h-16 w-10 object-cover" alt="Flowbite Logo" />
              <div class="flex flex-col items-center justify-center gap-1">
                <span class="self-center text-3xl font-semibold whitespace-nowrap dark:text-white">SceloImage</span>
                <span class="self-center text-lg font-normal text-gray-500 whitespace-nowrap dark:text-white">Upscale Images</span>
              </div>
            </a>
          </div>
          <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                  <ul class="text-gray-600 dark:text-gray-400">
                      <li class="mb-4">
                          <a href="https://flowbite.com" class="hover:underline">Flowbite</a>
                      </li>
                      <li>
                          <a href="https://tailwindcss.com/" class="hover:underline">Tailwind CSS</a>
                      </li>
                  </ul>
              </div>
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Contact Developer</h2>
                  <ul class="text-gray-600 dark:text-gray-400">
                      <li class="mb-4">
                          <a href="www.linkedin.com/in/talha-shahid-khan" class="hover:underline ">LinkedIN</a>
                      </li>
                      <li class="mb-4">
                          <a href="https://x.com/TSKhan_5429" class="hover:underline">X</a>
                      </li>
                      <li>
                        <a href="mailto:talhashahidkhan49@gmail.com" class="hover:underline">talhashahidkhan49@gmail.com</a>
                      </li>
                  </ul>
              </div>
          </div>
          
      </div>
  </div>
</footer>
    <script>{% block exscript %}{% endblock exscript %}</script>
    <script src="{% static "./js/flowbite.min.js" %}"></script>
    <script src="{% static "./js/htmx.min.js" %}"></script>
    <script>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    </script>
    <script>
      var themeToggleDarkIcon = document.getElementById(
        "theme-toggle-dark-icon"
      );
      var themeToggleLightIcon = document.getElementById(
        "theme-toggle-light-icon"
      );

      // Change the icons inside the button based on previous settings
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        themeToggleLightIcon.classList.remove("hidden");
      } else {
        themeToggleDarkIcon.classList.remove("hidden");
      }

      var themeToggleBtn = document.getElementById("theme-toggle");

      themeToggleBtn.addEventListener("click", function () {
        // toggle icons inside button
        themeToggleDarkIcon.classList.toggle("hidden");
        themeToggleLightIcon.classList.toggle("hidden");

        // if set via local storage previously
        if (localStorage.getItem("color-theme")) {
          if (localStorage.getItem("color-theme") === "light") {
            document.documentElement.classList.add("dark");
            localStorage.setItem("color-theme", "dark");
          } else {
            document.documentElement.classList.remove("dark");
            localStorage.setItem("color-theme", "light");
          }

          // if NOT set via local storage previously
        } else {
          if (document.documentElement.classList.contains("dark")) {
            document.documentElement.classList.remove("dark");
            localStorage.setItem("color-theme", "light");
          } else {
            document.documentElement.classList.add("dark");
            localStorage.setItem("color-theme", "dark");
          }
        }
      });
    </script>
  </body>
</html>

templates/cloud/ai.html
{% extends "base.html" %}
{% block title %}Use Image AI features{% endblock title %}
{% block body %}
<section class="bg-gray-200 dark:bg-gray-900">
    <div class="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
        <img class="w-full dark:hidden" src="{{img}}" alt="dashboard image">
        <img class="w-full hidden dark:block" src="{{img}}" alt="dashboard image">
        <div class="mt-4 md:mt-0">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Choose one AI feature to apply on your Image.</h2>
            <div class="flex item-center justify-start  flex-col gap-4">
                <form action="{% url "cloud:ups" pID %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-900">Upscale</button>
                </form>
                <form action="{% url "cloud:enhance" pID %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-900">AI Enhance</button>
                </form>
                <form action="{% url "cloud:fill" pID %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-900">Generative Fill [1:1]</button>
                </form>
               
                <form action="{% url "cloud:bgrmv" pID %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-900">BG Remove</button>
                </form>
            </div>
            <div class="mt-4">
                
            <form class="w-1/2 md:w-full flex flex-col items-start justify-center gap-4  md:mx-auto " action="{% url "cloud:replace" pID %}" method="post">
                {% csrf_token %}
                <label for="email-address-icon" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Replace</label>
                <input name="from" type="text" id="email-address-icon" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Replace from">
                <label for="email-address-icon" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">To</label>
                <input name="to" type="text" id="email-address-icon" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Replace to">
                <button type="submit" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-900">Generative Replace</button>
                </div>
            </form>
  
             
            </div>
        </div>
    </div>
</section>
{% endblock body %}

templates/cloud/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock title %}
{% load static %}
{% load widget_tweaks %}
{% block body %}


<section class="bg-gray-200 dark:bg-gray-900">
  <div class="grid grid-rows-2 lg:grid-rows-1 py-8 px-4 mx-auto max-w-screen-xl lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
      <div class="place-self-center mr-auto lg:col-span-7">
          <h1 class="mb-4 max-w-2xl text-4xl font-extrabold leading-none md:text-5xl xl:text-6xl dark:text-white">AI Image Manipulation Tool </h1>
          <p class="mb-6 max-w-2xl font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Powered by Cloudinary</p>
          <a  href="#upload" class="inline-flex justify-center items-center py-3 px-5 mr-3 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
              Upload Image
              <svg class="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </a>
          
      </div>
      <div class="lg:mt-0 lg:col-span-5 lg:flex border-gray-200 border-[10px] shadow-xl border-solid  rounded-md">
          <img src="{% static "./img/img2.png" %}" alt="mockup">
      </div>                
  </div>
</section>

<section class="bg-gray-50 dark:bg-gray-800">
  <div class="flex flex-col items-center justify-center py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
      <div class="mb-8 lg:mb-16 w-full">
          <h2 class="mb-4  text-4xl text-center font-extrabold text-gray-900 dark:text-white" id="upload"> Upload Image and Choose a service. </h2>
          <p class="text-gray-500 text-center sm:text-xl dark:text-gray-400">You can Upload 5 images in a day</p>
      </div>

    <form class="max-w-lg mx-auto flex items-center justify-center gap-8 flex-col" action="{% url "cloud:home" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% render_field form.image  class+="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"  type="file" id="input_field" %} 
        <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">Upload Photo to use our service.</div>
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Upload</button>
    </form>
      
  </div>
</section>

<section class="bg-gray-200 dark:bg-gray-900">
  <div class="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
      <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
          <h2 class="mb-4 text-4xl font-extrabold text-gray-900 dark:text-white">Try before any image editor</h2>
          <p class="mb-4">Transform your images effortlessly with cutting-edge AI tools! Whether you need to upscale quality, enhance details, creatively fill or replace parts of your image, or remove backgrounds with precision, our platform does it all. Skip the complexity of traditional image editors and experience instant, professional results. Perfect for professionals, creators, and casual users alike—try it now and see the difference AI makes!</p>
      </div>
      <div class="grid grid-cols-2 gap-4 mt-8">
          <img class="w-full rounded-lg" src="{% static "/img/ph1.png" %}" alt="office content 1">
          <img class="mt-4 w-full rounded-lg lg:mt-10" src="{% static "./img/ph2.png" %}" alt="office content 2">
      </div>
  </div>
</section>








{% endblock body %}

{% block exscript %}
window.onload = function() {
    document.getElementById('input_field').value = '';
    }

function dropHandler(ev) {
    console.log("File(s) dropped");
  
    // Prevent default behavior (Prevent file from being opened)
    ev.preventDefault();
  
    if (ev.dataTransfer.items) {
      // Use DataTransferItemList interface to access the file(s)
      [...ev.dataTransfer.items].forEach((item, i) => {
        // If dropped items aren't files, reject them
        if (item.kind === "file") {
          const file = item.getAsFile();
          console.log(`… file[${i}].name = ${file.name}`);
        }
      });
    } else {
      // Use DataTransfer interface to access the file(s)
      [...ev.dataTransfer.files].forEach((file, i) => {
        console.log(`… file[${i}].name = ${file.name}`);
      });
    }
  }

  
function dragOverHandler(ev) {
    console.log("File(s) in drop zone");
  
    // Prevent default behavior (Prevent file from being opened)
    ev.preventDefault();
  }
  

{% endblock exscript %}

templates/extra/result.html
{% if img %}

<section class="bg-white dark:bg-gray-900">
    <div class="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
        <div class="mt-4 md:mt-0">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Here is your result image</h2>
            
        </div>
        <img class="w-full dark:hidden" src="{{img}}" alt="dashboard image">
    </div>
</section>

{% endif %}